# Generated by Django 4.1.4 on 2023-01-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("S_No", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=12)),
                ("Comment", models.TextField(max_length=300)),
                ("date", models.DateField()),
            ],
        ),
        migrations.DeleteModel(name="UserDetail",),
    ]
