# Generated by Django 4.1.4 on 2023-01-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contact_delete_userdetail"),
    ]

    operations = [
        migrations.RemoveField(model_name="contact", name="S_No",),
        migrations.RemoveField(model_name="contact", name="date",),
    ]
