# Generated by Django 4.1.5 on 2023-01-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_contact_s_no_remove_contact_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="Comment", new_name="comment",
        ),
        migrations.AlterField(
            model_name="contact", name="email", field=models.EmailField(max_length=200),
        ),
    ]
