# Generated by Django 4.1.5 on 2023-02-03 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0005_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkbox_text", models.CharField(max_length=100)),
                ("is_selected", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="slot",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
