# Generated by Django 4.1.5 on 2023-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_slott"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.CharField(max_length=100)),
                ("payment_id", models.CharField(max_length=100)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(name="Slott",),
    ]
